apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: entity-extractor
  namespace: seldon-mesh
  labels:
    app: chatbot-platform
spec:
  storageUri: gs://seldon-models/scv2/samples/mlserver_1.5.0/iris-sklearn
  requirements:
  - sklearn
  memory: 500Mi